### ISSUE TITLE
Unable to build on Xcode 12 GM

### ISSUE THREAD

**Issue by jigneshD11** [paytm/Paytm_iOS_All_in_One_SDK#10]
Getting below error while building on Xcode 12.  

`Failed to build module 'AppInvokeSDK' from its module interface; the compiler that produced it, 'Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)'`

**Comment by anilp220** [comment]
I am also facing the same issue, any work around?

**Comment by soumyavats** [comment]
Please make the below change 
 Build Libraries for Distribution to “Yes” in the framework’s build settings
