### ISSUE TITLE
Unable to return in the App after Paymnet.

### ISSUE THREAD

**Issue by AlokGroomefy** [paytm/Paytm_iOS_All_in_One_SDK#12]
After implementing the AppInvokeSDk in iOS.
 if Paytm App is not installed it is working fine (Redirect to webpage and delegates gets called off transaction),
But When Paytm app is installed:-
- Not redirecting to our app after a transaction.
- No delegate method is called after payment.

**Comment by jay2098** [comment]
How did you solved this?

**Comment by jay2098** [comment]
> After implementing the AppInvokeSDk in iOS.
> if Paytm App is not installed it is working fine (Redirect to webpage and delegates gets called off transaction),
> But When Paytm app is installed:-
> 
> * Not redirecting to our app after a transaction.
> * No delegate method is called after payment.

How did you solved this?  @AlokGroomefy

**Comment by AlokGroomefy** [comment]
You have to put some delay after returning back into app to perform next action.


Like if you are going to validate  transaction  api put some delay in it.

**Comment by jay2098** [comment]
What is happening in my case is I have integrated iOS sdk in my flutter app and on initiate transaction it opens paytm app and after the transaction is completed it redirects back to paytm home page and not my app what to do in that case?
