### ISSUE TITLE
Not working in Xcode 12.3

### ISSUE THREAD

**Issue by dipendra-sharma** [paytm/Paytm_iOS_All_in_One_SDK#16]
I'm getting below mention error. Anyone, please suggest how I can resolve this issue.

`Building for iOS Simulator, but the linked and embedded framework 'AppInvokeSDK.framework' was built for iOS + iOS Simulator.`

Thanks !!

**Comment by soumyavats** [comment]
yes.. please share your email id so that we can provide you with solution

**Comment by dipendra-sharma** [comment]
deependrasharma55@gmail.com

**Comment by soumyavats** [comment]
you can use the latest code available on github https://github.com/paytm/Paytm_iOS_All_in_One_SDK/, we have updated our SDK
