### ISSUE TITLE
paytmInvoke not working on my iPhone 

### ISSUE THREAD

**Issue by dhaval951** [paytm/Paytm_iOS_All_in_One_SDK#18]
```
func openPaytm()
    {        
        self.appInvoke.restrictAppInvokeFlow(restrict: false)
        let result = self.invokePaytmApp(txnToken: self.PaytmtxnToken, orderId: self.orderid, mid: self.MID, amount:  10)
     
    }
```
    
    
    func invokePaytmApp(txnToken: String, orderId: String, mid: String, amount : String) -> Bool {
            if let paytmInvokeURL:URL = URL(string: "paytm://merchantpayment?txnToken=(txnToken)&orderId=(orderId)&mid=(mid)&amount=(amount)") {
                let application:UIApplication = UIApplication.shared
                if (application.canOpenURL(paytmInvokeURL)) {
                    application.open(paytmInvokeURL, options: [:]) { (finish) in}
                    return true
                }
                else{
                    let callback_url = "https://securegw-stage.paytm.in/theia/paytmCallback?ORDER_ID=\(self.orderid)"
                    self.appInvoke.openPaytm(merchantId: self.MID, orderId: self.orderid, txnToken: self.PaytmtxnToken, amount:  10, callbackUrl : callback_url, delegate: self, environment: AIEnvironment.staging)
                    return false
                }
            }
            return false
        }`
        
      

-   But while app install from App Link: [https://testflight.apple.com/join/JyFVfGSJ](url)

Navigation Flow Like below:
        after pay click -> user navigate -> Paytm-FS app -> getting below message form app.
        
        getting this error:
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/1260272/107469302-81f8e580-6b8f-11eb-821f-f7396c35a5f0.png)

please give me solution of it @nikhilpaytm @prkhr @abhimskywalker @abhimskywalker @shreyagarwal

**Comment by soumyavats** [comment]
What's the version of the Paytm app?

**Comment by dhaval951** [comment]
Paytm-FS
Version : 8.16.2(1)

**Comment by soumyavats** [comment]
Please use  9.0.0 version

**Comment by dhaval951** [comment]
Please can you share that version link?
currently i m using this App Link: [`https://testflight.apple.com/join/JyFVfGSJ`](url)
from there i get 8.16.2(1) only .

**Comment by dhaval951** [comment]
@soumyavats  any update please provide 9.0.0 version Link so i can check it.
it already spend too much days on it :(

**Comment by soumyavats** [comment]
yes I am working on that will update it today itself

**Comment by dhaval951** [comment]
@soumyavats Thanks for Inform...waiting for your responce :)

**Comment by soumyavats** [comment]
@dhaval951 upload is done. Its in beta review. ETA 24hr

**Comment by soumyavats** [comment]
@dhaval951 please get the Paytm staging app again from the same link

**Comment by dhaval951** [comment]
@soumyavats  Thanks let me check and inform .

**Comment by dhaval951** [comment]
@soumyavats Still getting same error :

![image](https://user-images.githubusercontent.com/1260272/108022179-15299380-7046-11eb-8c30-85145aaa8cdf.png)

**Comment by soumyavats** [comment]
@dhaval951 as discussed over the phone please mail me at soumya.vats@paytm.com
