### ISSUE TITLE
Response issue

### ISSUE THREAD

**Issue by ErAshu** [paytm/Paytm_iOS_All_in_One_SDK#2]
I have interated All in One SDK, everyThing is fine but response didn't get in didFinish Method.

Can you tell me where i get the response when payment get successfully?

 

> AIHandler().openPaytm(merchantId: merchantId, orderId: orderId, txnToken: token, amount: amount, redirectionUrl: callbackURL, delegate: self)

> func didFinish(with success: Bool, response: [String : Any]) {
>         
> }

**Comment by mrdishant** [comment]
Hi,

If you are using this version, kindly do modify your code. 
 
Steps: 
 
1. Create a local variable of AIHandler 
example : private var appInvoke : AIHandler = AIHandler()
 
2. call openPaytm method
example: appInvoke.openPaytm(_,_,_,_).

**Comment by ErAshu** [comment]
Yes, i have implemented this.
