### ISSUE TITLE
Session Expired Error

### ISSUE THREAD

**Issue by ishteyaque06** [paytm/Paytm_iOS_All_in_One_SDK#20]
Hi, I am getting lost in space error
![Simulator Screen Shot - iPhone 12 Pro - 2021-04-03 at 01 03 24](https://user-images.githubusercontent.com/26569026/113546441-9c889180-9609-11eb-86e8-253ab2f65484.png)

**Comment by soumyavats** [comment]
you are testing this with staging mid or production mid?

**Comment by ishteyaque06** [comment]
I am using production mid. I tried with same app also but same issue there.

**Comment by soumyavats** [comment]
> I am using production mid. I tried with same app also but same issue there.

Please mail your mid, order id and initiate token request and response to  us at integration.dev@paytm.com

**Comment by ishteyaque06** [comment]
Thanks for support,

**Comment by mayank2212** [comment]
@ishteyaque06 Hey getting the same issue. How to resolve the same?

**Comment by ishteyaque06** [comment]
@mayank2212 , With new SDK  I was passing checksum in place txnToken, So I asked backend team to share txnToken instead checksum.

**Comment by NikhilGangurde** [comment]
I am sending txn_token but still getting the same issue.
also using staging mid.

**Comment by Prakash128-lab** [comment]
Please share your issue with details  to us at integration.dev@paytm.com

**Comment by ErAshu** [comment]
If i immediately back from Paytm Payment Page, then I got this response in delegate method.
`func didFinish(with status: AIPaymentStatus, response: [String : Any]) {}`
reponse.STATUS = "TXN_FAILURE"
reponse.RESPMSG = "Session Expired Exception"
response.ORDERID = ""

IF I Stay approx 10 sec, and then back button pressed then I got "User has not completed transaction." RESP MSG with valid OrderID.

Please have a look. I have integrated latest sdk. 
![Simulator Screen Shot - iPhone 11 - 2022-01-31 at 13 27 36](https://user-images.githubusercontent.com/4178384/151758403-2ff810b5-9d11-42c8-bec8-d3f03a46c095.png)

**Comment by Prakash128-lab** [comment]
Please share the project sample file to us at integration.dev@paytm.com for reproduce this issue .

**Comment by it4Testing** [comment]
Same issue here, but only with ios simulator. When I tried to do payment in android it responds correctly but not in ios.
It gives "{"BANKTXNID": "", "RESPCODE": "1006", "RESPMSG": "Session Expired Exception", "STATUS": "TXN_FAILURE"}"
this response in ios.

**Comment by Prakash128-lab** [comment]
Hi,Please mail your mid, order id like request and response to us at [integration.dev@paytm.com](mailto:integration.dev@paytm.com)

**Comment by suhaillilac** [comment]
> Same issue here, but only with ios simulator. When I tried to do payment in android it responds correctly but not in ios. It gives "{"BANKTXNID": "", "RESPCODE": "1006", "RESPMSG": "Session Expired Exception", "STATUS": "TXN_FAILURE"}" this response in ios.

did you fix it ??

**Comment by Prakash128-lab** [comment]
Hi ,Please provide the details and confirm on which environment your are getting this issue.

**Comment by ishteyaque06** [comment]
Error is bcz of transaction id, you need to change your back end services for getting transaction id instead of checksum. For android you need to pass check sum but for ios with new SDK you need transaction id

**Comment by RumitPatel** [comment]
I got the strange reason. We were testing the transaction in sandbox environment.
We experienced that this error occurred if Paytm app is installed in the testing-device.

After I removed the PayTm app from testing-device, it started working as expected.

**Comment by Prakash128-lab** [comment]
Hi, Please check with latest updated version. The issue has been fixed in updated version. If any issue let us know.

**Comment by CRSohan4** [comment]
Hi, even I am facing "Your Session has expired." error when I execute startTransaction() in flutter. any help will be appreciated

**Comment by thakaredipali** [comment]
@CRSohan4  Have you found solution for the "Your session has expired" platform exception. Because I am facing same problem if you have solved this issue please help me.

**Comment by Prakash128-lab** [comment]
@thakaredipali Please confirm the SDK version which you have used. Please  test with latest version.

**Comment by thakaredipali** [comment]
@Prakash128-lab I have used latest version.

**Comment by Prakash128-lab** [comment]
@thakaredipali Please share the request detail and response to us at [integration.dev@paytm.com](mailto:integration.dev@paytm.com)

**Comment by pfrgit** [comment]
I would like to share my experience with the "The session expired issue" issue.

Scenario: Staging, Android
Solution: Paytm documentation mentions that for the above scenario of (Staging, and Android), we will have to uninstall the previously installed Paytm App and install the version provided by Paytm PG. For login, we will have to use special login.

APK location
https://github.com/paytm/Paytm_Payments_Android_Sample_Apps/tree/master/Paytm-Staging-App

Login: 7777777777 
Password: Paytm12345

Hope it helps your situation too.

**Comment by namanshukla8707** [comment]
I am also integrating the paytm gateway and facing the similar error can anyone help?

**Comment by chirag-bytelab** [comment]
i am getting same issue how to solve it :
Same issue here, but only with ios simulator. When I tried to do payment in android it responds correctly but not in ios.
It gives "{"BANKTXNID": "", "RESPCODE": "1006", "RESPMSG": "Session Expired Exception", "STATUS": "TXN_FAILURE"}"
this response in ios.

**Comment by namanshukla8707** [comment]
My issue was from Paytm side so I contacted their support team and my issue
was resolved.
