### ISSUE TITLE
AppInvokeSDK.xcframework Invalid binary on testFlight build 

### ISSUE THREAD

**Issue by Manikarthi-vaiha** [paytm/Paytm_iOS_All_in_One_SDK#21]
Hello DevOps,

I have used AppInvokeSDK.xcframework it's working fine while am debugging with real devices and simulators as well
when uploaded to test flight showing invalid binary on test flight build.

**Comment by soumya-vats** [comment]
Hi please try with framework Embed without signing option

**Comment by Manikarthi-vaiha** [comment]
Thank you it's working fine @soumya-vats

**Comment by mohdzakir786** [comment]
@Manikarthi-vaiha Are you able to payment after upload build on test flight , framework Embed without signing option

**Comment by Manikarthi-vaiha** [comment]
@mohdzakir786 yes
