### ISSUE TITLE
Getting Session Expired Message with error code 1006

### ISSUE THREAD

**Issue by cnfuzedRk62** [paytm/Paytm_iOS_All_in_One_SDK#26]
Hi Team i am Facing issue while Making payment on Staging environment. Attaching ScreenShot as well
<img width="378" alt="Screenshot 2021-09-17 at 9 54 02 AM" src="https://user-images.githubusercontent.com/52038339/133724155-10f888c1-ce0c-42fe-bcd5-472509660374.png">
[.]([url](url))

Help me.

**Comment by soumyavats** [comment]
Hi, you have downloaded the paytm staging app from testflight?

**Comment by cnfuzedRk62** [comment]
Why there is need of downloading testflight app???

**Comment by soumyavats** [comment]
you are using all in one sdk?

**Comment by cnfuzedRk62** [comment]
Yes, it is.

**Comment by soumyavats** [comment]
please raise a mail on integration.dev@paytm.com with details consisting of your mid and sample orderid

**Comment by cnfuzedRk62** [comment]
Ok, will do that.

**Comment by cnfuzedRk62** [comment]
Hi @soumyavats  Thanks for you help. Now my issue is fixed.
