### ISSUE TITLE
Login Failed in Paytm Staging App.

### ISSUE THREAD

**Issue by dhirajReliance** [paytm/Paytm_iOS_All_in_One_SDK#33]
Not able to login in  Paytm staging app using  **7777777777** and static OTP **888888**.  Please share valid credential.

https://github.com/paytm/Paytm_iOS_All_in_One_SDK/assets/130728285/0570f75b-5d83-4378-bcee-a885f9a7b127

**Comment by rahul2bisht** [comment]
Hi dhiraj,

Please use password i.e Paytm12345 not the OTP

**Comment by dhirajReliance** [comment]
Please update the same in your documentation also.
