### ISSUE TITLE
how to restrict ios app not to open paytm app when open paytm in any iOS application swift 5

### ISSUE THREAD

**Issue by Pinturaj** [paytm/Paytm_iOS_All_in_One_SDK#34]

**Comment by rahul2bisht** [comment]
Hi Pinturaj,

Please use below method after appinvoke function to restrict paytm app to invoke
**appInvoke.restrictAppInvokeFlow(restrict: true)**

**Comment by Pinturaj** [comment]
> Hi Pinturaj,
> 
> Please use below method after appinvoke function to restrict paytm app to invoke **appInvoke.restrictAppInvokeFlow(restrict: true)**

Thanks you Rahul, but I got a solution fot this. Just we have to set enable isMobileVerificationRequired: "true"

**Comment by dhirajReliance** [comment]
> > Hi Pinturaj,
> > Please use below method after appinvoke function to restrict paytm app to invoke **appInvoke.restrictAppInvokeFlow(restrict: true)**
> 
> Thanks you Rahul, but I got a solution fot this. Just we have to set enable isMobileVerificationRequired: "true"

Where did you this @Pinturaj ?
