### ISSUE TITLE
Session Expired Exception

### ISSUE THREAD

**Issue by CoreTecghgfhfghg** [paytm/Paytm_iOS_All_in_One_SDK#35]
Paytm Callback Response:  ["BANKTXNID": , "RESPCODE": 1006, "RESPMSG": Session Expired Exception, "STATUS": TXN_FAILURE]
![Screenshot 2023-10-21 at 4 45 05 PM](https://github.com/paytm/Paytm_iOS_All_in_One_SDK/assets/43535719/1a012ae2-fca7-444b-8e02-1ee2fe505e9e)

**Comment by rahul2bisht** [comment]
Hi,

This exception generally occurs due to the following reasons:
1. Using transaction token older than 15 mins.
2. Using wrong credentials (MID and Key).
3. Selecting wrong environment corresponding to credentials used.

**Comment by CoreTecghgfhfghg** [comment]
But When I tried to do payment in android it responds correctly with same credentials but not in ios. Can you tell me the way how to identify what the actual issue is.

**Comment by CoreTecghgfhfghg** [comment]
> Hi,
> 
> This exception generally occurs due to the following reasons:
> 
> 1. Using transaction token older than 15 mins.
> 2. Using wrong credentials (MID and Key).
> 3. Selecting wrong environment corresponding to credentials used.

But When I tried to do payment in android it responds correctly with same credentials but not in ios. Can you tell me the way how to identify what the actual issue is.
