### ISSUE TITLE
AppInvokeSDK.framework 'AIWebVC' not loaded

### ISSUE THREAD

**Issue by joshichirag70** [paytm/Paytm_iOS_All_in_One_SDK#8]
app was crash with below description (swift 5)

2020-08-19 19:38:11.966222+0530 MyStudyCanada[670:285219] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle </var/containers/Bundle/Application/99322906-D852-451C-8D67-15754F27183C/MyStudyCanada.app/Frameworks/AppInvokeSDK.framework> (loaded)' with name 'AIWebVC' and directory 'Main.storyboardc''
*** First throw call stack:
(0x1ab7da98c 0x1aa9b39f8 0x1ab6e4bc0 0x1d7da5b60 0x1d8277c64 0x102a3fe84 0x102a396c4 0x102a39550 0x102a39938 0x102b1b6f4 0x102b1cc78 0x102b2a6fc 0x1ab76c32c 0x1ab767264 0x1ab7667c0 0x1ad96779c 0x1d80ebc38 0x100f1ae74 0x1ab22a8e0)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by sumitGarg19** [comment]
Hi, 
Can you please let me know which Xcode version are you using?

**Comment by mahesh-rideziro** [comment]
I got same error and I m using xcode 11.6

**Comment by gokulkrizh** [comment]
Getting the same error on Xcode 11.5. 
Any ETA will be helpful.
@LalitChaudhary1 @himanshupaytm @nikhilpaytm

**Comment by keyur158** [comment]
Getting Same error on xcode 11.6 please let us know asap.
@LalitChaudhary1 

@joshichirag70 let us know if you found solution.

**Comment by jaisonfdo** [comment]
Hey team, facing the same issue on Xcode 11.5. Any updates?

**Comment by moumitachina** [comment]
Hello, I'm using Xcode 11.6 and getting this exact error. Please look into the matter so that we can get around with the integration.

**Comment by imthe1aboveall** [comment]
Hello Everyone, Can anyone please share the old version on this framework.

**Comment by keyur158** [comment]
Hello,

I used previous build bit it was buggy and even not working properly so
need to wait for his reply!!

Thank you

**Comment by imthe1aboveall** [comment]
> Hello, I used previous build bit it was buggy and even not working properly so need to wait for his reply!! Thank you
> […](#)

Thank you @keyur158

**Comment by ptvyas** [comment]
> @LalitChaudhary1 @himanshupaytm @nikhilpaytm
> I m getting this error after adding latest framework.

Any update for this issue?
otherwise, share the old framework! @LalitChaudhary1 @nikhilpaytm @himanshupaytm

**Comment by ssprs094** [comment]
I'm also facing the same issue in Xcode version 11.3

**Comment by keyur158** [comment]
Did anyone get a solution?

**Comment by paliwalmayankad** [comment]
I got same error and I m using xcode 12.0

**Comment by anilpahadiya** [comment]
I got same error and I m using xcode 12.0

**Comment by anilpahadiya** [comment]
please........
 Any update for this issue?

**Comment by joshichirag70** [comment]
This issue is solved in latest SDK.
